alma:
  api:
    token: xxxx
spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: xxxx
            clientSecret: xxxx
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xxxx
  datasource:
    password: paperless_paging_password
    url: jdbc:postgresql://localhost:5432/paperless_paging
    username: paperless_paging
